### ISSUE TITLE
Expose Competing Orders

### ISSUE THREAD

**Issue by jonallured** [artsy/exchange#372]
In order to work this ticket:

https://artsyproduct.atlassian.net/browse/SELL-1334

I'll need for Exchange to expose when there are better orders for a seller to pick. This only applies to MO offers and the two types of better orders are:

* a BN order at full price
* another MO offer at a higher price

In either of these situations, I'd like to be able to query for the order and get links to the better offers, something like this:

```
query($id: String!) {
  ecommerceOrder(id: $id) {
    id
    betterOrders {
      fullPriceOrder {
        id
      }
      higherPriceOffer {
        id
      }
    }
  }
}
```

So then when I'm consuming this query, I can check to see if those fields are null or not. If they are not null then we'll link to those orders in the header of the page, like so:

https://app.zeplin.io/project/5aabc6f28d835c7b2585fdf4/screen/5b72f58dd5475320522cb1dd

I actually don't even really care about anything other than the id because that's all I need in order to construct the link, but it's probably best to set ourselves up to return full Order types here so that future changes here will be cheap. For instance, I could see us wanting to show the price of higher offers. Something to think about.

Now, there are edges (and maybe others, but this is what I could think of):

* what if there are more than one BN full price orders?
* what if there are more than one MO higher price orders?

In the case of where there is more than one better order, we prefer the order placed earliest. In the case where there are more than one MO higher offers, we take the highest one and break any ties by when they were placed.

Thoughts, questions, ideas?

**Comment by iskounen** [comment]
It may be interesting to link users back to the list of orders, filtered to only include those orders that are "better" than a given order. This would allow the user to browse and compare those orders without having to go back to the "worse" order.

**Comment by sweir27** [comment]
@jonallured cool!

The way you have  your schema right now, I would definitely expect to receive a full order/offer when queried way. If you wanted to have a boolean field to check (as opposed to checking presence of one of  those) you could add a boolean field like `hasBetterOffer`. That wouldn't really provide any more data, but is another potential pattern. What you have seems 👍 .

Your logic for de-duping makes sense to me. I'm interested in how we'll do this on exchange's side!

**Comment by ashkan18** [comment]
This is an interesting case, thinking out loud, i think the word `betterOrders` is little vague and not as explicit about what `better` is, maybe we could call it something like
`similarOrders` and then have sort and filtering options on it? so something like
```graphql
query($id: String!) {
  bnOrders: ecommerceSimilarOrder(id: $id, mode: BUY, sort: CREATED_AT) {
    id
  }
  moOrders: ecommerceSimilarOrder(id: $id, mode: OFFER, sort: OFFER_PRICE) {
    id
  }
}
```

My guess is if there are any BN orders then we don't even show offers as options, right?

**Comment by jonallured** [comment]
Awesome feedback, thanks friends! After reading this and pondering, I'm seeing two directions:

* Clients define what "better" means and Exchange merely exposes queries to support them
* Exchange is in charge of what "better" means

The approach we see in @ashkan18's comment lines up with that first approach - Exchange provides a query that takes an order id and finds all competing orders with the ability to filter and sort what's returned.

The approach I was spitballing in the issue description is closer to that second option, but taken to the extreme would look like this:

```gql
query($id: String!) {
  ecommerceOrder(id: $id) {
    id
    betterOrder {
      id
      mode
    }
  }
}
```

So here I'm leaving the definition of what "better" means up to Exchange and as a client I can just see if that field is nil or not to know whether to draw that highlight in CMS.

And CMS is actually the only client that will have to do this, so I think [Rule of Three](https://en.wikipedia.org/wiki/Rule_of_three_(computer_programming)) kicks in and we should go in the direction @ashkan18 is proposing. I might suggest using the word competing rather than similar, but I think this is the way to go.

Unless there's any other feedback here I'll go ahead and start a branch for this.

Thanks again!! 😍 

PS: @iskounen yeah I think that's something we've been kicking around but is out of scope for the ticket I'm working. There's a comp for making the order list page more fancy with searching and filtering but we descoped it early on in the project until we learn more. 👍

**Comment by sweir27** [comment]
Maybe as a compromise, we could name it something like `competingOrder`/`competingOffer`?

**Comment by orta** [comment]
If you know the [view model](https://en.wikipedia.org/wiki/Model–view–viewmodel) pattern, that's basically what I think about metaphysics. I see it as existing to augment data from elsewhere in favor of simplifying front end code. Which is basically re-saying what Chris mentioned.

I think @damassi's abstractions are fine, and will continue to work in a pure schema-stitched world of MP too. Which we're close with ( https://github.com/artsy/metaphysics/pull/1463 ) 

It's like exchange provides all the primitives, and how those data models are stitched together is the responsibility of metaphysics.
