### ISSUE TITLE
Do we need a pending state (in the first version)?

### ISSUE THREAD

**Issue by yuki24** [artsy/exchange#55]
I just have reviewed the design mockups, and I strongly think that we do **not** need both pending and abandoned states in the `Order` model.

### What problems would `pending` bring in?

 * An order record that was actually placed by the user usually consists of de-normalized data while any order prior to that state could either be a set of meta data or de-normalized data but without required fields. Saving two different types of data in one table would require us to have different validation rules and data structures in the same place depending on the state. This is very fragile and prone to human errors.
 * It would create the need of handling garbage data. There is already https://github.com/artsy/exchange/issues/26, and there will be more. One example is duplicate pending orders created by the user on different devices. Unique index would solve it, but again that would be unnecessary if there was no pending order.

### What should we do instead?

 * The backend should accept two mutations: `CreateEstimation` and `CreateOrder`. Every time the user changes the order criteria, the client should call the `CreateEstimation` mutation to get a new estimate.
 * `CreateEstimation` creates a new estimation based on the information the user has provided. This mutation should return the best possible estimate if called **without** required fields.
 * When placing order, the client calls `CreateOrder`, the backend makes a diff between what's posted and the last estimate, and if there's no diff it'll hold the amount. It will also de-normalize the order data so the user is free to change the address or credit card in Gravity without affecting the order the user just placed.

> I checked with Brian about the naming, and the name `estimate` does not sound right to him. I'm also open to suggestions, but it really is an estimate. The other term I used was "Order preview", but it still doesn't seem to reflect what we are displaying the flow.

### Could the `createEstimation` mutation just be `createPendingOrder`?

 * My proposed solution could possibly solve all the problems that the `pending` state could solve (though as always, I could be missing something).
 * Adding a separate table is as simple as (or even simpler than) maintaining two or more states in one table because you don't have to worry about breaking data integrity in the `orders` table when you add run a migration against the `estimations` table, or vice versa.
 * Merging two tables is easier than extracting one type of data out of one table.
 * One typical requirement for a e-commerce service is that users should be able to get a quote without all the required information (do not assume the user has provided all the info we request when we call `createEstimation`). This means even users without Artsy accounts may have to be able to get an estimation. If we went with the `UpdateOrder` mutation path, we would have to accommodate all this logic in one action, which becomes more difficult as you add more logic.

**Comment by ashkan18** [comment]
Thanks @yuki24 for writing this up. This is interesting, I would like to understand your design a little bit more in details. 
As far as I understand, you are suggesting not creating orders till they actually submit it. Before submitting orders we create _estimates_, few questions about that:
- Are you planning to keep these estimates around? do we end up creating same amount of garbage data?
- When user enters their credit card, they haven't yet submitted their order, do we associate their credit card id to an estimate object? When one goes from payment page to confirmation page, is credit card id stored on client side?

In general in terms of garbage data, im not personally worried about `pending` and `abandoned` orders, as long as there is an easy way for filtering them out. I think to some extend they actually have some useful data and facts in them.

When had a chance lets actually plan something and go over design together, I really like immutability part of your design, we are currently tracking state changes in our audit log using `papertrail`.

**Comment by williardx** [comment]
I'm going to close this out because we decided on pending orders ⚡️
