### ISSUE TITLE
CreateOrder weirdness

### ISSUE THREAD

**Issue by ashkan18** [artsy/exchange#75]
# Current state
Current `createOrder` mutation requires `partnerId`, a list of line items in which we require an artwork.

# Weirdness points
We set `partnerId` on an `Order` but it's actually related directly to the artworks in the order line items. With current mutation it's technically possible for someone to call this mutation, set `partnerId` to partner A but add artworks of partner B to the line items.
We talked about not requiring `partnerId` in the mutation and from exchange we fetch the partner Id , this is also as weird as the current solution since exchange basically has to find the first artwork in the line items (ignoring all other artworks) and from that artwork, set `Orders`'s `partnerId` which seems super weird.

This is all because of the fact that an order can have multiple line items (potentially multiple artworks) but belongs to specific partner. So we need to make sure all line items of an order belong to the partner of that order.

# Possible solution A

### Provide `createOrderFromArtwork` mutation
```graphql
mutation createOrderFromArtwork(input: {artworkId: String!, editionsetId: String, quantity: Int})
```
This way we start from line item and we make sure this order can only have one line item (matching our current front end rules.

Later when we started supporting multiple artwork purchases from a partner we can provide 
```graphql
mutation createOrder(input: {partnerId: String!})
```
and 
```graphql
mutation addLineItem(input: {artworkId: String!, editionsetId: String})
```
and in ☝️we make sure artworkId being added to the order belongs to the order's partner.

# Possible Solution B
Enforce 1-1 relation between order and line items, basically an order can have only one line item. This would solve our problem of assuming partner id from line items but the issue here is this modeling won't be realistic over time.

# Proposed solution
Go with option **A** as more flexible and closer to reality option.

**Comment by sweir27** [comment]
👍 Option A seems good to me since it models our current reality but allows the model to stay flexible.

**Comment by williardx** [comment]
Option A sounds good to me, too.
